baseURL = "https://shoogle.us/massachusetts"
languageCode = "en-US"
title = "Massachusetts"
theme = "ln-base-en"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "massachusetts"
